apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: testpod6
  name: testpod6
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: testpod6
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: testpod6
    spec:
      containers:
      - image:  node
        imagePullPolicy: Always
        name: testpod6
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
